application: dc2jpr
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /data/.*
  script: data.py
- url: /compose/.*
  script: compose.py
- url: /input/.*
  script: input.py
- url: /dc/.*
  script: track.py
- url: /
  script: index.py
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

builtins:
- remote_api: on
- datastore_admin: on
