application: dc2j
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /data/.*
  script: data.py
- url: /compose/.*
  script: compose.py
- url: /input/.*
  script: input.py
- url: /
  script: index.py

